title: "GEONMIN LEE — AI/Multimodal Portfolio"
subtitle: "문서 AI · 표 구조 복원 · Qwen 계열 멀티모달"
description: "Qwen2.5/3-VL 기반 표 구조 복원, 문서 임베딩·검색, Mermaid 코드화 파이프라인 포트폴리오"
lang: ko
timezone: Asia/Seoul
url: "https://geonmin0607.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache

search: true

author:
  name: "GEONMIN LEE"
  avatar: "/assets/images/avatar.png"
  bio: "Document AI · Multimodal · Table HTML Extraction · QLoRA"
  location: "Seoul, Korea"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/geonmin0607"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:"

collections:
  projects:
    output: true
    permalink: /projects/:name/
  pocs:
    output: true
    permalink: /pocs/:name/
  patents:
    output: true
    permalink: /patents/:name/

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: single
      author_profile: true
      toc: true
      toc_sticky: true
      classes: wide
      sidebar:
        nav: "main"
  - scope:
      path: ""
      type: "pocs"
    values:
      layout: single
      author_profile: true
      toc: true
      toc_sticky: true
      classes: wide
      sidebar:
        nav: "main"
  - scope:
      path: ""
      type: "patents"
    values:
      layout: single
      author_profile: true
      toc: false
      classes: wide
      sidebar:
        nav: "main"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true
      toc: true

collections_dir: ""
permalink: /:categories/:title/

markdown: kramdown
kramdown:
  input: GFM
  math_engine: "katex"

exclude:
  - "node_modules"
  - "README.md"
  - "Gemfile"
  - "Gemfile.lock"

logo: "/assets/images/logo.png"
