collections:
  projects:
    output: true
    permalink: /projects/:name/
  patents:
    output: true
    permalink: /patents/:name/
  tech:
    output: true
    permalink: /tech/:name/

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: single
      author_profile: true
      toc: true
      toc_sticky: true
      classes: wide
      sidebar:
        nav: "main"
      show_date: false
  - scope:
      path: ""
      type: "patents"
    values:
      layout: single
      author_profile: true
      toc: false
      classes: wide
      sidebar:
        nav: "main"
      show_date: false
  - scope:
      path: ""
      type: "tech"
    values:
      layout: single
      author_profile: true
      toc: true
      toc_sticky: true
      classes: wide
      show_date: false
