title: "GEONMIN LEE —  AI 엔지니어"
subtitle: "LLM, Multimodal Portfolio"
description: "LLM 및 멀티모달(문서·표·다이어그램·차트) 기반 프로젝트/특허 포트폴리오"
lang: ko
timezone: Asia/Seoul
url: "https://geonmin0607.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache

search: true

author:
  name: "GEONMIN LEE"
  bio: "LLM & Multimodal · Document AI · Table HTML Extraction"
  location: "Seoul, Korea"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/geonmin0607"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:"

collections:
  projects:
    output: true
    permalink: /projects/:name/
  patents:
    output: true
    permalink: /patents/:name/
  tech:
    output: true
    permalink: /tech/:name/

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: single
      author_profile: true
      toc: true
      toc_sticky: true
      classes: wide
      sidebar:
        nav: "main"
      show_date: false
  - scope:
      path: ""
      type: "patents"
    values:
      layout: single
      author_profile: true
      toc: false
      classes: wide
      sidebar:
        nav: "main"
      show_date: false
  - scope:
      path: ""
      type: "tech"
    values:
      layout: single
      author_profile: true
      toc: true
      toc_sticky: true
      classes: wide
      show_date: false
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true
      toc: true

permalink: /:categories/:title/

markdown: kramdown
kramdown:
  input: GFM
  math_engine: "katex"

exclude:
  - "node_modules"
  - "Gemfile"
  - "Gemfile.lock"
